{"name": "test_three", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 2", "trace": "self = <test_mark-study.Test_Demo2 object at 0x000002304C16F188>\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.smoke\n    @pytest.mark.demo\n    def test_three(self):\n        b=2\n>       assert 0==b#注意这个用例会失败\nE       assert 0 == 2\n\ntest_mark-study.py:20: AssertionError"}, "start": 1618744810791, "stop": 1618744810792, "uuid": "78129f80-5b55-4f99-bf09-90c3a7b793ca", "historyId": "196a7b2f808184d3aa37ab27bb1dd4ca", "testCaseId": "fd43668bea87f65c1f45d86f693ce928", "fullName": "test_mark-study.Test_Demo2#test_three", "labels": [{"name": "tag", "value": "smoke"}, {"name": "tag", "value": "demo"}, {"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_mark-study"}, {"name": "subSuite", "value": "Test_Demo2"}, {"name": "host", "value": "LAPTOP-RIERPE4G"}, {"name": "thread", "value": "22744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark-study"}]}